# https://github.com/compose-spec/compose-spec/blob/master/spec.md
# https://www.docker.com/blog/developing-docker-windows-app-wsl2/
# Reference project: https://github.com/shekhargulati/python-flask-docker-hello-world

version: "3.3"
services:
  web:
    build: .
    ports:
      - 5000:5000
    command: python -m priv_tube.api run
    environment:
      FLASK_DEBUG: '1'
      FLASK_APP: priv_tube.api
    volumes:
      - ./:/app
