# Compose spec: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# https://www.docker.com/blog/developing-docker-windows-app-wsl2/
# Reference flask project: https://github.com/shekhargulati/python-flask-docker-hello-world

version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    ports:
      - 5000:5000
    entrypoint: python -m priv_tube.api run
    environment:
      FLASK_DEBUG: '1'
      FLASK_APP: priv_tube.api
      DB_LOCATION: /app/app.db
    volumes:
      - ./:/app
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/database.dockerfile
    environment:
      FLASK_DEBUG: '1'
      FLASK_APP: priv_tube.api
      DB_LOCATION: /app/app.db
    volumes:
      - ./docker/db_init.sh:/app/docker/db_init.sh
      - ./:/app
