# Compose spec: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# https://www.docker.com/blog/developing-docker-windows-app-wsl2/
# Reference flask project: https://github.com/shekhargulati/python-flask-docker-hello-world

version: "3.3"
services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: docker/api.dockerfile
    ports:
      - 5000:5000
    entrypoint: python -m priv_tube.api run
    environment:
      FLASK_DEBUG: '1'
      FLASK_APP: priv_tube.api
      DB_LOCATION: /app/data/app.db
    volumes:
      - ./priv_tube:/app/priv_tube
      - ./data:/app/data
    depends_on:
      - database
      - grafana
      - influx
      - chronograf
      - keycloak

  database:
    hostname: db
    build:
      context: .
      dockerfile: ./docker/database.dockerfile
    environment:
      FLASK_DEBUG: '1'
      FLASK_APP: priv_tube.api
      DB_LOCATION: /app/data/app.db
    volumes:
      - ./docker/db_init.sh:/app/docker/db_init.sh
      - ./priv_tube:/app/priv_tube
      - ./data:/app/data

  keycloak_db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    hostname: keycloak
    image: quay.io/keycloak/keycloak:17.0.0
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    depends_on:
      - keycloak_db

  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana # Where user data goes.  Make it a host volume unless you want to recreate stuff every time you boot

  influx:
    hostname: influx
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin # Initial setup requires that
      DOCKER_INFLUXDB_INIT_PASSWORD: admin # Initial setup requires that
    ports:
      - 8086:8086

  chronograf:
    hostname: chronograf
    image: chronograf:latest
    ports:
      - 8888:8888

volumes:
  mysql_data:
      driver: local