# https://github.com/compose-spec/compose-spec/blob/master/spec.md
# https://www.docker.com/blog/developing-docker-windows-app-wsl2/

version: "3.3"
services:
  web:
    build: .
    network_mode: host
    ports:
      - "5000:5000"
    command: python /app/api.py
    volumes:
      - ./priv_tube:/app
    # command:
    # - gunicorn
    # - app.wsgi
    # - --bind=0.0.0.0:5000
    # - --workers=${WEB_CONCURRENCY:-1}
    # - --preload
    # - --access-logfile=-
